CREATE OR REPLACE DATABASE MANAGE_DB;
CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE
    url="s3://snowflake-tutorial-aryan/OrderDetails.csv"
    credentials=(aws_key_id=''
        aws_secret_key='');

DESC STAGE MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE

LIST @AWS_STAGE;

CREATE OR REPLACE TABLE MANAGE_DB.EXTERNAL_STAGES.orders(
ORDER_ID VARCHAR(30),
AMOUNT INT,
PROFIT INT,
QUANTITY INT,
CATEGORY VARCHAR(255),
SUBCATEGORY VARCHAR (30)
)

SELECT * FROM MANAGE_DB.EXTERNAL_STAGES.orders;

COPY INTO MANAGE_DB.EXTERNAL_STAGES.orders
FROM @AWS_STAGE
FILE_FORMAT=(type= CSV FIELD_DELIMITER="," SKIP_HEADER=1)

CREATE OR REPLACE TABLE MANAGE_DB.EXTERNAL_STAGES.ordersx(
    ORDER_ID VARCHAR(30),
    CATEGORY VARCHAR(255)
)

COPY INTO MANAGE_DB.EXTERNAL_STAGES.ORDERSX
FROM (SELECT s.$1, s.$5 from @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
file_format=(type= csv field_delimiter=","skip_header=1)

SELECT * FROM MANAGE_DB.EXTERNAL_STAGES.ORDERSX;

CREATE OR REPLACE TABLE MANAGE_DB.EXTERNAL_STAGES.orderspro(
ORDER_ID VARCHAR(30),
AMOUNT INT,
PROFIT INT,
CATEGORY_PRO VARCHAR(255)
)

COPY INTO MANAGE_DB.EXTERNAL_STAGES.ORDERSPRO
FROM (SELECT
    s.$1,
    s.$2,
    s.$3,
    CASE WHEN CAST(s.$3 as INT)<0 THEN 'not profitable' ELSE 'PROFITABLE' END
    FROM @MANAGE_DB.EXTERNAL_STAGES.AWS_STAGE s)
file_format=(type=csv field_delimiter=',' skip_header=1)

SELECT * FROM MANAGE_DB.EXTERNAL_STAGES.ORDERSPRO;
